v0.1
Signed-off-by: Andreas Karis <ak.karis@gmail.com>

diff --git a/gather b/gather
--- a/gather
+++ b/gather
@@ -1,11 +1,12 @@
 #!/bin/bash
 
-set -eu
+set -eux
 
 VERBOSE=true
 EXTRACT_TIMEOUT=600s
+RESOURCE_DIR="${RESOURCE_DIR:-"/resources"}"
 BASE_COLLECTION_PATH="must-gather"
-LOG_PATH="${BASE_COLLECTION_PATH}/pmd_logs"
+DATA_DIR="${BASE_COLLECTION_PATH}/collect-pmd-info"
 
 # verbose can be enabled or disabled on demand
 verbose () {
@@ -13,19 +14,8 @@ verbose () {
 }
 
 wait_for() {
-  local pod_name="${1}"
-  kubectl wait --for=condition=Ready pod "${pod_name}" --timeout="${EXTRACT_TIMEOUT}" &
-  local pid1=$!
-  kubectl wait --for=jsonpath='{.status.phase}'=Failed pod "${pod_name}" --timeout="${EXTRACT_TIMEOUT}" &
-  local pid2=$!
-  while kill -0 "${pid1}" && kill -0 "${pid2}"; do
-      verbose "Waiting for pod condition to be met for pod ${pod_name}"
-      sleep 5
-  done
-  if ! kill -0 "${pid1}"; then
-    return 0
-  fi
-  return 1
+  local daemonset_name="${1}"
+  kubectl rollout status ds "${daemonset_name}" --timeout="${EXTRACT_TIMEOUT}"
 }
 
 get_collection_image() {
@@ -37,122 +27,113 @@ get_collection_image() {
     kubectl get pods "${pod_name}" -o jsonpath='{.spec.containers[0].image}'
 }
 
+# save_collector_logs gets the logs of all containers of all data collectors and stores them in the must-gather.
 save_collector_logs() {
-    local pod_name
-    pod_name="$1"
+    local daemonset_label="${1}"
 
-    verbose "Saving logs from collector pod '${pod_name}'"
-
-    kubectl logs -c data-collector "${pod_name}" > "/must-gather/${pod_name}.log"
+    pushd "${DATA_DIR}"
+    for pod in $(kubectl get pods -o name -l "${daemonset_label}"); do
+        verbose "Saving logs from pod '${pod}'"
+        kubectl logs -c data-collector "${pod}" > "${pod/pod\//}.log"
+    done
+    popd
 }
 
+# save_data copies all collected data from the collectors to the must-gather pod.
+save_data() {
+    local daemonset_label="${1}"
+    local container_name="${2}"
+
+    pushd "${DATA_DIR}"
+    for pod in $(kubectl get pods -o name -l "${daemonset_label}"); do
+        verbose "Copying data from pod '${pod}'"
+        mkdir -p "${pod}"
+        kubectl cp -c "${container_name}" "${pod/pod\//}:/data-store" "${pod}"
+    done
+    popd
+}
+
+# collect_data modifies the kustomization data, spawns the DaemonSet and waits for the DaemonSet's init containers
+# (= data collectores) to finish. It saves both the logs and data, then it deletes the DaemonSet.
+# The only thing that distinguishes a successful run from a failed run is the success / WARNING message. The reason
+# for this is that even if the scripts time out, etc., we want to capture all the data that we gathered up to this
+# point.
 collect_data() {
-    local node
-    node="$1"
-    local pod_name
-    pod_name="$2"
-    local image
-    image="$3"
-    local process
-    process="$4"
+    local daemonset_name="${1}"
+    local daemonset_label="${2}"
+    local image="${3}"
+    local node_name="${4}"
+    local process="${5}"
 
-    verbose  "Collecting data for node: '${node}', pod_name: '${pod_name}', image: '${image}', process: '${process}'"
+    verbose  "Spawning daemonset: '${daemonset_name}', daemonset_label: '${daemonset_label}'"
+    set_daemonset_image "${image}"
+    set_daemonset_environment_variables "${process}"
+    set_daemonset_node_selector "${node_name}"
+    run_daemonset
 
-    run_data_collection_pod "${node}" "${pod_name}" "${image}" "${process}"
-    if wait_for "${pod_name}"; then
+    if wait_for "${daemonset_name}"; then
         verbose  "Data collection succeeded"
-        save_collector_logs "${pod_name}"
-        kubectl cp -c sleep-infinity "${pod_name}:/must-gather" /must-gather
-        kubectl delete pod "${pod_name}"
+        save_collector_logs "${daemonset_label}"
+        save_data "${daemonset_label}" "sleep-infinity"
+        delete_daemonset
     else
-        verbose  "Data timed out or failed"
-        save_collector_logs "${pod_name}"
-        kubectl delete pod --force --grace-period=0 "${pod_name}"
+        verbose  "WARNING: Data timed out or failed"
+        save_collector_logs "${daemonset_label}"
+        save_data "${daemonset_label}" "network-metrics"
+        delete_daemonset
     fi
 }
 
-run_data_collection_pod() {
-    local node
-    node="$1"
-    local pod_name
-    pod_name="$2"
-    local image
-    image="$3"
-    local process
-    process="$4"
+# set_daemonset_image modifies the kustomization.yaml and specifies a new image to use for the collector pods.
+set_daemonset_image() {
+    local image="${1}"
 
-    cat << EOF | kubectl apply -f -
-apiVersion: v1
-kind: Pod
-metadata:
-  name: ${pod_name}
-  labels:
-    name: gather-pmd
-spec:
-  initContainers:
-  - command:
-    - collect
-    - ${process}
-    env:
-    - name: TMOUT
-      value: "900"
-    image: ${image}
-    imagePullPolicy: Always
-    name: data-collector
-    resources: {}
-    securityContext:
-      privileged: true
-      runAsUser: 0
-    terminationMessagePath: /dev/termination-log
-    terminationMessagePolicy: File
-    volumeMounts:
-    - mountPath: /host
-      name: host
-    - mountPath: /must-gather
-      name: data-store
-  containers:
-  - command:
-    - sleep
-    - infinity
-    image: ${image}
-    imagePullPolicy: Always
-    name: sleep-infinity
-    volumeMounts:
-    - mountPath: /must-gather
-      name: data-store
-  dnsPolicy: ClusterFirst
-  enableServiceLinks: true
-  hostIPC: true
-  hostNetwork: true
-  hostPID: true
-  nodeName: ${node}
-  preemptionPolicy: PreemptLowerPriority
-  priority: 1000000000
-  priorityClassName: openshift-user-critical
-  restartPolicy: Never
-  schedulerName: default-scheduler
-  securityContext: {}
-  serviceAccount: default
-  serviceAccountName: default
-  terminationGracePeriodSeconds: 30
-  tolerations:
-  - effect: NoExecute
-    key: node.kubernetes.io/not-ready
-    operator: Exists
-    tolerationSeconds: 300
-  - effect: NoExecute
-    key: node.kubernetes.io/unreachable
-    operator: Exists
-    tolerationSeconds: 300
-  volumes:
-  - hostPath:
-      path: /
-      type: Directory
-    name: host
-  - emptyDir:
-      sizeLimit: 10Gi
-    name: data-store
-EOF
+    verbose "Setting IMAGE='${image}'"
+
+    sed -i "s#^  newName:.*#  newName: ${image}#" "${RESOURCE_DIR}/kustomization.yaml"
+}
+
+# set_daemonset_environment_variables sets INTERVAL and DURATION in patch-env.json (which in turn is added to the
+# DaemonSet's pods' environment).
+set_daemonset_environment_variables() {
+    local process="${1}"
+    local tmp_file
+    tmp_file=$(mktemp)
+    jq '(.spec.template.spec.initContainers[] | select(.name == "data-collector") | .env[] | select(.name == "TIMEOUT") | .value) |= "'"${EXTRACT_TIMEOUT}"'"' \
+    "${RESOURCE_DIR}/patch-env.json" > "${tmp_file}"
+    cp "${tmp_file}" "${RESOURCE_DIR}/patch-env.json"
+    jq '(.spec.template.spec.initContainers[] | select(.name == "data-collector") | .env[] | select(.name == "PROCESS") | .value) |= "'"${process}"'"' \
+        "${RESOURCE_DIR}/patch-env.json" > "${tmp_file}"
+    cp "${tmp_file}" "${RESOURCE_DIR}/patch-env.json"
+    verbose "New environment file is: $(cat "${RESOURCE_DIR}"/patch-env.json)"
+    rm -f "${tmp_file}"
+}
+
+# set_daemonset_node_selector sets .spec.template.spec.nodeName.
+set_daemonset_node_selector() {
+    local node_name="${1}"
+
+    local tmp_file
+    tmp_file=$(mktemp)
+    jq ".spec.template.spec.nodeName = \"${node_name}\"" "${RESOURCE_DIR}/patch-selector.json" > "${tmp_file}"
+    cp "${tmp_file}" "${RESOURCE_DIR}/patch-selector.json"
+
+    verbose "New node selector is: $(cat "${RESOURCE_DIR}/patch-selector.json")"
+    rm -f "${tmp_file}"
+}
+
+# run_daemonset applies the DS inside the current namespace.
+run_daemonset() {
+    pushd "${RESOURCE_DIR}"
+    kubectl apply -k .
+    popd
+}
+
+# delete_daemonset deletes the DS from the current namespace.
+delete_daemonset() {
+    pushd "${RESOURCE_DIR}"
+    kubectl delete -k .
+    popd
 }
 
 NODE_NAME="${NODE_NAME-""}"
@@ -167,11 +148,12 @@ if [ -z "${POD_NAME}" ]; then
 fi
 process="${1:-}"
 if [ "${process}" == "" ]; then
-    echo "Please provided a process ID or process name."
+    echo "Please provided a process ID or process name"
     exit 1
 fi
 
-mkdir -p "${LOG_PATH}"
-cd "${LOG_PATH}"
+mkdir -p "${DATA_DIR}"
 image=$(get_collection_image "${POD_NAME}")
-collect_data "${NODE_NAME}" collect-pmd-info "${image}" "${process}"
+daemonset_name=collect-pmd-info
+daemonset_label="app=collect-pmd-info"
+collect_data "${daemonset_name}" "${daemonset_label}" "${image}" "${NODE_NAME}" "${process}"
